apiVersion: v1
kind: Namespace
metadata:
  name: sock-shop
---
apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: mysql-disk
spec:
  capacity:
    storage: "200Gi"
  accessModes:
    - "ReadWriteOnce"
  gcePersistentDisk:
    fsType: "ext4"
    pdName: "mysql-disk"
  claimRef:
    name: mysql-disk
    namespace: sock-shop
---
apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: mongo-orders
spec:
  capacity:
    storage: "200Gi"
  accessModes:
    - "ReadWriteOnce"
  gcePersistentDisk:
    fsType: "ext4"
    pdName: "mongo-orders"
  claimRef:
    name: mongo-orders
    namespace: sock-shop
---
apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: mongo-carts
spec:
  capacity:
    storage: "200Gi"
  accessModes:
    - "ReadWriteOnce"
  gcePersistentDisk:
    fsType: "ext4"
    pdName: "mongo-carts"
  claimRef:
    name: mongo-carts
    namespace: sock-shop
---
apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: mongo-users
spec:
  capacity:
    storage: "200Gi"
  accessModes:
    - "ReadWriteOnce"
  gcePersistentDisk:
    fsType: "ext4"
    pdName: "mongo-users"
  claimRef:
    name: mongo-users
    namespace: sock-shop
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql-disk
  namespace: sock-shop
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongo-carts
  namespace: sock-shop
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongo-orders
  namespace: sock-shop
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongo-users
  namespace: sock-shop
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
